name: frontend-ci-workflow

on:
  # Run on demand
  workflow_dispatch:
  # Run when pull request to main branch
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment.
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      
      # Cache action to restore cache.

      # Install the dependencies.
      - run: cd starter/frontend && npm ci

      # Run the linter.
      - run: cd starter/frontend && npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment.
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      
      # Cache action to restore cache.

      # Install the dependencies.
      - run: cd starter/frontend && npm ci

      # Run the test.
      - run: cd starter/frontend && npm run test
      
  build:
    needs: [lint, test]

    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment.
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # Cache action to restore cache.

      # Install the dependencies.
      - run: cd starter/frontend && npm ci

      # Build the application.
      - run:

      # Send a console message at completion.
      - run: |
          echo "Front end build complete"
